[package]
name = "cmp_wrap"
version = "0.1.0"
description = "Let you compare structes by context"
license = "MIT"
authors = ["ori <oriashur155@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
